**NumPy stands for Numerical Python. It has following features** : 

**POWERFUL N-DIMENSIONAL ARRAYS** : Fast and versatile, the NumPy vectorization, indexing, and broadcasting concepts are the de-facto standards of array computing today.

**NUMERICAL COMPUTING TOOLS** : NumPy offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.

**INTEROPERABLE** : NumPy supports a wide range of hardware and computing platforms, and plays well with distributed, GPU, and sparse array libraries.

**PERFORMANT** : The core of NumPy is well-optimized C code. Enjoy the flexibility of Python with the speed of compiled code.

**EASY TO USE** : NumPy’s high level syntax makes it accessible and productive for programmers from any background or experience level.

**OPEN SOURCE** : Distributed under a liberal BSD license, NumPy is developed and maintained publicly on GitHub by a vibrant, responsive, and diverse community.


**DATASET** :The dataset used to demonstrate the functions of numpy is related to red and white variants of the Portuguese "Vinho Verde" wine.Columns of the datasets include:


- fixed acidity
- volatile acidity
- citric acid
- residual sugar
- chlorides
- free sulfur dioxide
- total sulfur dioxide
- density
- pH
- sulphates
- alcohol
- quality (score between 0 and 10)

**1-Load Dataset using **:
 Data is captured from the CSV file into a list which is then converted into a numpy array with the help of np.array
  function

In [3]:
import csv
with open("winequality-redcsv.csv", 'r') as f:
    wines = list(csv.reader(f, delimiter=";"))
import numpy as np
wines = np.array(wines[1:], dtype=float)

**2-Shape**:We can check the number of rows and columns in our data using the shape property of NumPy arrays:

In [4]:
wines.shape

(1599, 12)


**3-Slicing** :
Inorder to select first 4 items from the fourth column, we can use (:). Colon indicates that we want to select all the elements from the starting index up to but not including the ending index. It is called slicing:




In [3]:
wines[0:3,3]

array([1.9, 2.6, 2.3])

**3.1-Column Selection using Slicing** :We can select an entire column by specifying that we want all the elements, from the first to the last. We specify this by just using the colon (:), with no starting or ending indices. The below code will select the entire fourth column:



In [5]:
wines[:,3]

array([1.9, 2.6, 2.3, ..., 2.3, 2. , 3.6])

**4-Indexing the array** :
In the below code, we pass in index 2 as the row index, and the index 3 as the column index. This retrieves the value from the fourth column of the third row:

In [21]:
wines[3,4]

0.075

**5-Convert 2D array into a 1D array** : Ravel function of numpy array flattens into a long sequence of values

In [6]:
wines.ravel()

array([ 7.4 ,  0.7 ,  0.  , ...,  0.66, 11.  ,  6.  ])

**6-Reshape Function** : Reshape function is used to reshape the array with specified rows and columns.For example third row of wines can be converted into a 2-dimensional array with 2 rows and 6 columns:



In [21]:
wines[2,:].reshape((2,6))

array([[7.80e+00, 7.60e-01, 4.00e-02, 2.30e+00, 9.20e-02, 1.50e+01],
       [5.40e+01, 9.97e-01, 3.26e+00, 6.50e-01, 9.80e+00, 5.00e+00]])

**Combining two numpy arrays** : We can combine multiple arrays into a single array.We can retrieve data from winequality-white.csv dataset that contains information on the quality of white wines, and combine it with our existing dataset, wines, which contains information on red wines. Therefore information is read from the database of white wines by the below code

In [22]:
whitewines = np.genfromtxt("winequality-white.csv", delimiter=";", skip_header=1)
whitewines.shape

(4898, 12)

**7-Vstack Function** :Then we can use vstack function to combine wines and whitewines datasets vertically by the below code.After combining the number of rows increases while number of columns remains the same

In [23]:
combinedwines = np.vstack((wines, whitewines))
combinedwines.shape

(6497, 12)

We can also use hstack function to combine wines and whitewines datasets horizontally by the below code.After combining the number of column increases while number of rows remains the same. The code is shown below:

**8-Concatenate Function**: We can also use concatenate function to combine two arrays along axis. Conacetaninting along first axis is hstack(along the rows) while second axis is vstack(along the columns). The syntax is as follows:

In [25]:
np.concatenate((wines, whitewines), axis=0)

array([[ 7.4 ,  0.7 ,  0.  , ...,  0.56,  9.4 ,  5.  ],
       [ 7.8 ,  0.88,  0.  , ...,  0.68,  9.8 ,  5.  ],
       [ 7.8 ,  0.76,  0.04, ...,  0.65,  9.8 ,  5.  ],
       ...,
       [ 6.5 ,  0.24,  0.19, ...,  0.46,  9.4 ,  6.  ],
       [ 5.5 ,  0.29,  0.3 , ...,  0.38, 12.8 ,  7.  ],
       [ 6.  ,  0.21,  0.38, ...,  0.32, 11.8 ,  6.  ]])

**9-Sum Function**: If we want total sum of quality score from red wine dataset, we need to call the sum function in the below code. Since it is the last column we need to use -1 in the index of numpy array.

In [28]:
qualitysums = wines[:, -1].sum()
print(qualitysums)

9012.0


**10-Mean Function**: We can also find the mean quality score using mean function given below: 

In [29]:
meanquality = wines[:, -1].mean()
print(meanquality)

5.6360225140712945
